start_simulation: 2023-06-01
end_simulation: 2024-05-31
start_cutoff: 2022-01-01
end_cutoff: 2024-05-31
training_mode: "long"
PCT_QTY_ORDER: 0.1
initial_balance: 100000
treshold_price: 0.00001
processing: local
seq_length: 120
timing: false
chunk_size: 20000
episodes: 20
chunk_epochs: 10
num_processes: 10