start_simulation: 2023-01-01
end_simulation: 2024-05-31
start_cutoff: 2022-01-01
end_cutoff: 2024-05-31
training_mode: "long"
PCT_QTY_ORDER: 0.1
initial_balance: 100000
treshold_price: 0.00001
processing: local
seq_length: 30
timing: true