start_simulation: 2023-01-01
end_simulation: 2023-08-31
start_cutoff: 2022-01-01
end_cutoff: 2023-08-31
training_mode: "long"
PCT_QTY_ORDER: 0.1
initial_balance: 100000
treshold_price: 0.00001
processing: local
seq_length: 60
timing: false
chunk_size: 4000
chunk_epochs: 10
num_processes: 10